import {Platform, StyleSheet} from 'react-native';
import {Colors} from '../constants/Colors';
import Responsive from '../constants/Responsive';
import SpStyle from './SpStyle';
import TextStyles from './TextStyles';

const CmnStyles = StyleSheet.create({
  screenBG: {backgroundColor: Colors.bgColorText2, flex: 1},
  screenBG2: {backgroundColor: Colors.white, flex: 1},
  bottomBarIcon: {
    width: 26,
    height: 26,
  },
  focusedBottomBarButtonStyle: {
    shadowColor: Colors.black,
    shadowOffset: {
      width: 0,
      height: 7,
    },
    shadowOpacity: 0.41,
    shadowRadius: 9.11,
    elevation: 14,
  },
  bottomBarContainerStyle: {
    position: 'absolute',
    bottom: 0,
    left: 0,
    right: 0,
  },
  SplashBG: {
    backgroundColor: Colors.bgColor,
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
  },
  splashTop: {
    width: Responsive.widthPx(35),
    height: Responsive.widthPx(60),
    justifyContent: 'flex-end',
    paddingBottom: Responsive.widthPx(10),
  },
  splashImage: {
    width: Responsive.widthPx(35),
    height: Responsive.widthPx(35),
  },
  splashTextBox: {
    height: Responsive.widthPx(40),
  },
  splashText: {
    ...TextStyles.white_28_700,
    ...SpStyle.shadow,
  },
  loginLogo: {width: Responsive.widthPx(25), height: Responsive.widthPx(25)},
  loginTop: {
    height: Responsive.widthPx(50),
    justifyContent: 'flex-end',
    alignItems: 'center',
  },
  loginTitle: {
    ...TextStyles.white_21_700,
    marginLeft: Responsive.widthPx(5),
    marginTop: Responsive.widthPx(8),
    marginBottom: Responsive.widthPx(16),
    textAlign: 'center',
  },
  updateProBox2: {backgroundColor: Colors.white},
  loginInputBox: {
    width: Responsive.widthPx(92),
    height: Responsive.widthPx(13),
    marginBottom: Responsive.widthPx(12),
    backgroundColor: Colors.white,
    borderRadius: Responsive.widthPx(2),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    ...SpStyle.shadowLight,
  },
  loginInput: {
    paddingLeft: Responsive.widthPx(3),
    ...TextStyles.black16_Reg,
    marginBottom: Platform.OS == 'ios' ? 3 : 0,
    width: '100%',
  },
  loginCode: {
    paddingLeft: Responsive.widthPx(5),
    ...TextStyles.black15_SemiBold,
  },
  loginButtonBox: {
    width: Responsive.widthPx(92),
    height: Responsive.widthPx(13),
    backgroundColor: Colors.white,
    borderRadius: Responsive.widthPx(2),
    alignSelf: 'center',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    ...SpStyle.shadow,
  },
  loginButtonText: {...TextStyles.orange_18_700},
  loginButtonText2: {...TextStyles.white_19_700},
  otpIMG: {
    width: Responsive.widthPx(30),
    height: Responsive.widthPx(30),
    alignSelf: 'center',
    marginVertical: Responsive.widthPx(9),
  },
  otpBackImg: {
    width: Responsive.widthPx(5),
    height: Responsive.widthPx(5),
    tintColor: Colors.white,
    marginBottom: Responsive.widthPx(5),
    marginRight: Responsive.widthPx(3),
  },
  otpBackImgCont: {
    padding: Responsive.widthPx(5),
  },
  otpTitle: {...TextStyles.white_24_600, alignSelf: 'center'},
  otpText: {
    ...TextStyles.white_14_400,
    textAlign: 'center',
    width: Responsive.widthPx(94),
    marginVertical: Responsive.widthPx(6),
  },
  otpScreenCont: {alignItems: 'center'},
  OtpResendBox: {
    alignItems: 'center',
    justifyContent: 'center',
    // marginTop: Responsive.widthPx(6),
  },
  OtpButton: {
    marginTop: Responsive.widthPx(6),
  },
  myHeaderCont: {
    height: Responsive.heightPx(7.5),
    backgroundColor: Colors.bgColorText2,
    paddingHorizontal: Responsive.widthPx(6),
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
  myHeaderText: {
    ...TextStyles.white_21_700,
    alignSelf: 'center',
  },
  myHeaderProImg: {
    width: Responsive.widthPx(7),
    height: Responsive.widthPx(7),
    tintColor: Colors.white,
  },
  proScreenTopPartCont: {
    padding: Responsive.widthPx(4),
    paddingTop:
      Platform.OS === 'ios' ? Responsive.widthPx(16) : Responsive.widthPx(6),
    backgroundColor: Colors.bgColor,
    position: 'absolute',
    top: 0,
    width: Responsive.widthPx(100),
    height: Responsive.widthPx(90),
  },
  proScreenTopPartBox: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    paddingRight: Responsive.widthPx(2),
  },
  proScreenTopPartImg: {
    width: Responsive.widthPx(32),
    height: Responsive.widthPx(32),
    marginTop: Responsive.widthPx(6),
    borderRadius: Responsive.widthPx(12),
    alignSelf: 'center',
    backgroundColor: Colors.white,
  },
  proScreenTopPartText: {
    ...TextStyles.white_21_700,
    alignSelf: 'center',
    marginVertical: Responsive.widthPx(5),
  },
  proScreenTopPartText2: {
    ...TextStyles.black15_SemiBold,
    alignSelf: 'center',
    marginLeft: Responsive.widthPx(2),
  },
  proScreenData: {
    marginTop: Responsive.widthPx(70),
    backgroundColor: Colors.white,
    borderTopLeftRadius: Responsive.widthPx(10),
    borderTopRightRadius: Responsive.widthPx(10),
    paddingVertical: Responsive.widthPx(3),
  },
  proScreenDataBox: {
    paddingVertical: Responsive.widthPx(4),
    marginBottom: Responsive.widthPx(20),
    paddingHorizontal: Responsive.widthPx(6),
    overflow: 'hidden',
  },
  updateProHeader: {
    width: Responsive.widthPx(100),
    height: Responsive.widthPx(13),
    backgroundColor: Colors.bgColorText,
    alignItems: 'center',
    justifyContent: 'center',
  },

  headerOrangeDark: {
    position: 'absolute',
    height: Responsive.widthPx(13),
    width: Responsive.widthPx(100),
    top: 0,
    backgroundColor: Colors.bgColorText,
  },
  closeButton: {
    height: Responsive.widthPx(4.5),
    width: Responsive.widthPx(4.5),
    tintColor: Colors.white,
  },
  closeButtonBox: {
    height: Responsive.widthPx(4.5),
    width: Responsive.widthPx(4.5),
    position: 'absolute',
    left: Responsive.widthPx(7),
  },
  updateProHeaderText: {
    ...TextStyles.white_21_700,
  },
  businessLogoUploadBox: {
    width: Responsive.widthPx(40),
    ...SpStyle.shadowLight,
    borderRadius: Responsive.widthPx(50),
    height: Responsive.widthPx(40),
    marginTop: Responsive.widthPx(8),
    backgroundColor: Colors.white,
    paddingVertical: Responsive.widthPx(5),
    borderWidth: 0.5,
    borderColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  businessLogoUploadBox2a: {
    width: Responsive.widthPx(30),
    ...SpStyle.shadowLight,
    borderRadius: Responsive.widthPx(4),
    height: Responsive.widthPx(20),
    marginTop: Responsive.widthPx(8),
    backgroundColor: Colors.white,
    paddingVertical: Responsive.widthPx(5),
    borderWidth: 0.5,
    borderColor: Colors.gray,
    alignItems: 'center',
    justifyContent: 'center',
    alignSelf: 'center',
  },
  businessLogoUploadBox2: {
    alignSelf: 'center',
    marginTop: Responsive.widthPx(8),
  },
  businessLogoUploadImage3: {
    width: Responsive.widthPx(12.5),
    height: Responsive.widthPx(12.5),
    marginBottom: Responsive.widthPx(4),
    tintColor: Colors.bgColorText2,
  },
  businessLogoUploadImage4: {
    width: Responsive.widthPx(7),
    height: Responsive.widthPx(4),
    marginBottom: Responsive.widthPx(2),
    tintColor: Colors.bgColorText2,
  },
  businessLogoUploadImage2: {
    height: Responsive.widthPx(40),
    width: Responsive.widthPx(40),
    borderRadius: Responsive.widthPx(20),
  },
  businessLogoUploadImage2a: {
    height: Responsive.widthPx(20),
    width: Responsive.widthPx(30),
    borderRadius: Responsive.widthPx(4),
  },
  f1AlignJustCenterAbs: {
    flex: 1,
    position: 'absolute',
    alignItems: 'center',
    justifyContent: 'center',
  },
  updateProBox: {
    marginTop: Responsive.widthPx(5),
    paddingHorizontal: Responsive.widthPx(3),
    width: Responsive.widthPx(88),
    marginBottom: 0,
    borderColor: Colors.gray,
    borderRadius: Responsive.widthPx(1),
    ...SpStyle.shadowLight,
  },
  updateProDateBox: {
    marginTop: Responsive.widthPx(5),
    paddingHorizontal: Responsive.widthPx(6),
    width: Responsive.widthPx(88),
    marginBottom: 0,
    borderColor: Colors.gray,
    borderRadius: Responsive.widthPx(1),
    ...SpStyle.shadowLight,
  },
  uploadFileCont: {
    marginTop: Responsive.widthPx(4),
    marginBottom: Responsive.widthPx(4),
    flexDirection: 'row',
  },
  uploadFileBox: {
    flexDirection: 'row',
    width: Responsive.widthPx(55),
  },
  uploadFileImg: {
    width: Responsive.widthPx(8),
    height: Responsive.widthPx(8),
    marginLeft: Responsive.widthPx(4),
  },
  uploadFileImgText: {
    width: Responsive.widthPx(38),
    marginLeft: Responsive.widthPx(4),
    ...TextStyles.Orange_12_600,
  },
  chooseFileBox: {
    width: Responsive.widthPx(24),
    borderRadius: 8,
    backgroundColor: Colors.grayLight,
    height: Responsive.widthPx(7),
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 0.4,
    marginLeft: Responsive.widthPx(10),
  },
  updateProDataCont: {
    paddingBottom: Responsive.widthPx(10),
  },
  uploadFileText: {
    alignSelf: 'flex-end',
    marginLeft: Responsive.widthPx(3),
    marginBottom: Responsive.widthPx(1),
  },
  updateButton: {
    marginTop: Responsive.widthPx(6),
    width: Responsive.widthPx(88),
    backgroundColor: Colors.bgColor,
  },
  profileDataCardBox: {
    flexDirection: 'row',
    width: Responsive.widthPx(88),
    // height: Responsive.widthPx(14),
    paddingVertical: Responsive.widthPx(4),
    ...SpStyle.shadowLight,
    backgroundColor: Colors.white,
    borderRadius: Responsive.widthPx(4),
    alignItems: 'center',
    paddingLeft: Responsive.widthPx(4),
    marginTop: Responsive.widthPx(4),
    alignSelf: 'center',
  },
  smallLogo: {
    width: Responsive.widthPx(4.5),
    height: Responsive.widthPx(4.5),
    marginRight: Responsive.widthPx(1),
    tintColor: Colors.bgColorText,
  },
});

export default CmnStyles;
